# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1819bccff8c31f905ba00840e16d9158c3603e64d0d3f038938affd7cb93ed16a689ecab434921c43eeb1bd4c61cc3f2bf9aceb0dc5318342bf0fab97e920fda

test:
  secret_key_base: ff91cc269ae53a9e08bc5a3f92a371c487b6fec9ee66002aab416c05bd053b006a5535f0a7e9b434790e050c418da1e1e53a56d4910cda00896d454eac871e9f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
